services:
  - type: web
    name: jayhind-yadav-portfolio
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_1VvEQKWxYgT8@ep-misty-resonance-b54ndn9o-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
